dist: trusty

sudo: required

language: cpp

# BEGIN BUILD MATRIX
#
# Build matrix must be smaller on branch coverity_scan because quota allows
# only 5 Coverity Scan jobs at once. Thus we have different versions of this
# file on branch master and coverity_scan.
#
# Please keep this file as much in sync as possible to allow easy merging
# from master into coverity_scan and only have differences in the build
# matrix block.
#
# Check the difference as follows:
#   $ git checkout master
#   $ git checkout coverity_scan
#   $ git difftool master coverity_scan .travis.yml
os:
  - linux

compiler:
  - gcc

git:
  depth: 5

cache:
  ccache: true
  directories:
    - $HOME/.sonar/cache

install:
  - ./src/scripts/ci/travis/install.sh

script:
  - if [ "${COVERITY_SCAN_BRANCH}" != 1 ]; then ./src/scripts/ci/travis/build.sh ; fi

after_success:
  - ./src/scripts/ci/travis/after_success.sh

notifications:
  email: botan-commits@lists.randombit.net

addons:
  sonarqube: true

  coverity_scan:
    project:
      name: "randombit/botan"
    notification_email: lloyd@randombit.net
    build_command_prepend: "./configure.py --cc-bin=/usr/bin/g++-4.8"
    build_command: "make -j2"
    branch_pattern: coverity_scan
